services:
  - type: web
    name: verixaai
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
